### ISSUE TITLE
configure MTA for BaseEmail

### ISSUE THREAD

**Issue by bararchy** [luckyframework/carbon#10]
how do I do this^ :)

**Comment by paulcsmith** [comment]
Hey @bararchy! Can you describe what you mean by MTA? I've not heard of that before

**Comment by bararchy** [comment]
@paulcsmith Sorry for later response, MTA stands for mail transfer agent and usually is refereed when talking of the next step an SMTP based client should go to to send emails.

What I was asking is how I tell carbon to send emails via x.x.x.x:25 etc.. and not using other service\site

**Comment by bararchy** [comment]
@paulcsmith I see, makes sense then, i was kinda surprised to find no SMTP support builtin because it's kinda the basis of email technology.

anyway, I'll see if I can make it my weekend project :)

**Comment by paulcsmith** [comment]
@bararchy Yeah that makes sense. It's so much easier to work with SendGrid and most people prefer it (I think) but it would be *awesome* to have an SMTP adapter as well! If you get it working feel free to open an issue here and I'll add it to the README so people can use it. LMK if you need any help with the adapter
