### ISSUE TITLE
Difference with lucky views

### ISSUE THREAD

**Issue by zenati** [luckyframework/carbon#12]
@paulcsmith 
Hello,

In Lucky, tags are generated with regular Crystal methods, and Carbon, on the other side, uses ECR.

Why is that ? Isn't it better to have both generated with crystal methods for typesafe templates ?

Thanks.

**Comment by paulcsmith** [comment]
This is a great question, and it’s one I’m still debating. One big difference is that with regular pages me and my team have a lot of control over the HTML. 

For emails we often use templates that have lots of inlined CSS and complex comments to conditionally show things in different email clients. 

So for simple html templates crystal methods would be great, but for more complex ones it would require rewriting lots of large and complex templates. 

What I may do is have an option to use Lucky store tags or ECR depending on what you need. 

The other option would be to have a really good html to Lucky concerted that did such a good job that you could just convert it to Lucky and it would all work just fine. 

For now I think ECR is the safest. Then I’ll add support for Lucky pages, then once he converter has all the edge cases down, Lucky style will be the default. Does that make sense?

**Comment by paulcsmith** [comment]
Oh and one more reason, ECR will always be supported because some people may want to use Carbon with other frameworks where they’re already using ECR, so this would fit in their workflow better.

**Comment by paulcsmith** [comment]
I'll close this question now, but will hopefully have time to implement some nice helpers with Lucky views for creating emails soon!
