### ISSUE TITLE
Allow `puts`ing emails in the `DevAdapter`

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/carbon#14]
https://github.com/luckyframework/carbon/issues/3#issuecomment-398207669

* Add an optional `print_emails` option to the `DevAdapter`
* Default it to `false`

```crystal
Carbon::DevAdapter.new(print_emails: true)
```

Will `puts` the email when delivering. This would go in this method: https://github.com/luckyframework/carbon/blob/e58a02452349a0505411c7ff86508a65212da4da/src/carbon/adapters/dev_adapter.cr#L4-L6

**Comment by camuthig** [comment]
I'm looking to experiment with Crystal some, and am interested in helping out with this ticket. Is there any particular format you think would be best for the output?

**Comment by paulcsmith** [comment]
@camuthig That would be fantastic! I can't think of a particular format, but maybe something like this?

```
To: ...
From: ...
Subject: ...
Headers: ...
Text Body: ...
HTML Body: ...
```

I think those keys can be colorized as green so it's easier to differentiate between key value. You can use the colorize module built in to Crystal: https://crystal-lang.org/api/0.25.1/Colorize.html

LMK if you have any other questions. I'm happy to help :)
