### ISSUE TITLE
Instance variables not working in templates

### ISSUE THREAD

**Issue by RemiKalbe** [luckyframework/carbon#22]
I created a text and HTML template, I have a couple of instance variables but when the email is sent the variables aren't replaced by their value they stay like that `#{@name_of_the_variable}`.

My class is like that:

```crystal
class ConfirmationEmail < BaseEmail
    @title : String
    @sub_title : String
    @body : String

    def initialize(@email_address : String, @language : String, @confirmation_code : String)
      @title = translate("email_confirmation_title", @language, Nil)
      @sub_title = translate("email_confirmation_sub_title", @language, Nil)
      @body = translate("email_confirmation_body", @language, Nil)
    end

    to @email_address
    subject translate("email_confirmation_subject", @language, Nil)
    reply_to "no-reply@dwoom.com"
    templates text, html
  end
```

Here is my text template, couldn't be simpler:

```ecr
#{@title}
#{@sub_title}

#{@body}


#{@confirmation_code}
```

I won't show my HTML template it's way too big. And I don't think it matters as the issue also involve the text template.

So when the email is sent, I receive the email like that:

```ecr
#{@title}
#{@sub_title}

#{@body}


#{@confirmation_code}
```

Not, with the actual values.

Am I doing something wrong here?

**Comment by RemiKalbe** [comment]
I figured it out!

I replaced
```
#{@name_of_the_variable}
```
by
```
<%= @name_of_the_variable -%>
```

( from https://crystal-lang.org/api/0.21.1/ECR.html )

And now it works!

**Comment by y2k2mt** [comment]
I got same.
I created a new PR.
https://github.com/luckyframework/carbon/pull/35

**Comment by paulcsmith** [comment]
Glad you got this figured out, and sorry for the confusion in the README!
