### ISSUE TITLE
SendInBlue adapter

### ISSUE THREAD

**Issue by brunto** [luckyframework/carbon#37]
We are working on a SendInBlue adapter https://github.com/atnos/carbon_send_in_blue_adapter still in development, we need to add CC, BCC, and REPLY_TO support.

**Comment by jwoertink** [comment]
Are you saying your adapter needs to add those? Because I think Carbon already has CC, BCC, and REPLY_TO support.

**Comment by brunto** [comment]
We need to map Carbon with the SendInBlue API for instance here https://github.com/atnos/carbon_send_in_blue_adapter/blob/master/src/carbon_send_in_blue_adapter.cr#L36 we need to add `replyTo` instead of `reply_to` https://github.com/luckyframework/carbon/blob/master/src/carbon/adapters/send_grid_adapter.cr#L41

**Comment by paulcsmith** [comment]
Hi @brunto! Just to clarify, do we need to do anything in Carbon or can this be handled in your adapter? If it can be handled in your adapter I'll go ahead and close this

**Comment by brunto** [comment]
Hi @paulcsmith I can handle this inside the adapter. You can close this issue.

**Comment by jwoertink** [comment]
Thanks for your work on this @brunto. That will be a nice adapter for the community.
