### ISSUE TITLE
Extract SendGrid adapter into separate shard

### ISSUE THREAD

**Issue by stephendolan** [luckyframework/carbon#46]
Our README already has a great list of community Carbon adapters, and I believe that SendGrid should just be a Lucky-maintained third party adapter.

It struck me as a bit odd that we have default support for a single vendor in the Carbon library itself, and while it's nice to have an out-of-the-box solution that works in production, we can get around that by including the extracted shard in applications generated with the Lucky CLI.

Resolution of this issue should occur in these steps:
- Extract SendGrid support to a separate adapter in the `luckyframework` org
- Remove SendGrid support from this repository
- Submit a PR to the Lucky CLI to include the new adapter in default Lucky generated apps
- Ensure that release notes are loud and clear that this is a breaking change for anyone currently relying on SendGrid, and that they'll need to add the shard to their apps.

**Comment by matthewmcgarvey** [comment]
Created this repo: https://github.com/luckyframework/carbon_sendgrid_adapter
