### ISSUE TITLE
Why is colorize undefined?

### ISSUE THREAD

**Issue by kingsleyh** [luckyframework/carbon#57]
```
In lib/carbon/src/carbon/adapters/dev_adapter.cr:25:16

 25 | "#{"To:".colorize(:green)} #{email.to}",
               ^-------
Error: undefined method 'colorize' for String
```

**Comment by matthewmcgarvey** [comment]
I think it's a missing import in Carbon https://crystal-lang.org/api/1.0.0/Colorize.html

**Comment by kingsleyh** [comment]
I added the `require "colorize"` to the file where I use carbon and it seems to be working now.

**Comment by paulcsmith** [comment]
Thanks for reporting this! Sounds like we need to require this in Carbon too. I'll open a PR

**Comment by paulcsmith** [comment]
It appears that the latest on master includes colorize through another shard and is tested in dev_adapter_spec, so I think we're good to go. Going to go ahead and close
