### ISSUE TITLE
`Carbon::Email` is no longer serializable

### ISSUE THREAD

**Issue by akadusei** [luckyframework/carbon#91]
I include `JSON::Serializable` in my emails to have them sent in the background with [Mel](https://github.com/GrottoPress/mel/blob/master/src/carbon/deliver_later_strategy.cr). Since Carbon v0.5, I get a compile error:

```
Showing last frame. Use --error-trace for full trace.

There was a problem expanding macro 'macro_139862332317072'

Code in /path/to/.crenv/versions/1.11.2/share/crystal/src/json/from_json.cr:271:3

 271 | {% begin %}
       ^
Called macro defined in /path/to/.crenv/versions/1.11.2/share/crystal/src/json/from_json.cr:271:3

 271 | {% begin %}

Which expanded to:

 > 27 |         
 > 28 |           when "io"
 > 29 |             __temp_4884 = self[:io].new(pull)
                                            ^--
Error: wrong number of arguments for 'IO::ARGF#initialize' (given 1, expected 2)
```

#88 introduced `@attachment` instance variable in `Carbon::Email`, a named tuple with one of its members being an `IO`, which is not serializable.

Is it possible to get rid of the `@attachment` instance variable? Maybe redefine `.attachment` macro thus:

```crystal
macro attachment(value)
    def attachments : Array(Carbon::Attachment)
      {% if @type.methods.map(&.name).includes?("attachments".id) %}
        previous_def | [value]
      {% else %}
        [value]
      {% end %}
    end
  end
```

Code above is not tested, so I'm not sure if it works. But I'm thinking along the same lines as the callbacks:

https://github.com/luckyframework/carbon/blob/0a814fd129f88528d9ec72b8e787e22a3af8be28/src/carbon/callbacks.cr#L24-L34

Or is there a better way to handle emails with *Mel* that I'm missing?

**Comment by jwoertink** [comment]
Ah, yeah. I think we can come up with a patch for this. What do you think @manveru ?
